//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Model1Container : DbContext
    {
        private static Model1Container containerContext;
        public static Model1Container getContainer()
        {
            if (containerContext  == null )
            {
                containerContext = new Model1Container();
        
            }
            return containerContext;
        }

        private Model1Container()
            : base("name=Model1Container")
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MyItems> MyItems { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Dinamic> Dinamics { get; set; }
    }
}
