//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyItems()
        {
            this.People = new HashSet<Person>();
            this.Dinamics = new HashSet<Dinamic>();
        }
    
        public int IId { get; set; }
        public string IPath { get; set; }
        public string IName { get; set; }
        public string IDescription { get; set; }
        public string IType { get; set; }
        public string IDate { get; set; }
        public string IIsPhoto { get; set; }
        public string IMark { get; set; }
        public string IDelete { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
        public virtual Place Place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dinamic> Dinamics { get; set; }
    }
}
